### ISSUE TITLE
Crash when switching sectors

### ISSUE THREAD

**Issue by Thermi** [Casimir255/SeamlessClient#10]
Happened to me with the new built when I joined a server and clicked on one med room, let it load, then chose another one in a different sector, waited for it to load, and clicked respawn:

```
2024-07-21 08:18:01.183 - Thread:  12 ->  Initialized large grid Desolo Main Base 60288 PCU
2024-07-21 08:18:10.520 - Thread:   1 ->  SeamlessClient: Beginning Redirect to server: 90200203979886610
2024-07-21 08:18:11.092 - Thread:   1 ->  NexusSyncMod.ModCore
2024-07-21 08:18:11.093 - Thread:   1 ->  Jakaria.API.WaterModAPI
2024-07-21 08:18:11.135 - Thread:   1 ->  CoreSystems.Session
2024-07-21 08:18:11.146 - Thread:   1 ->  DefenseShields.Session
2024-07-21 08:18:11.148 - Thread:   1 ->  MIG.SpecCores.GameBase
2024-07-21 08:18:11.149 - Thread:   1 ->  Example.Mod
2024-07-21 08:18:11.150 - Thread:   1 ->  DualCockpits.CockpitSessionComponent
2024-07-21 08:18:11.150 - Thread:   1 ->  AtmosphericDamage.DamageCoreSun
2024-07-21 08:18:11.150 - Thread:   1 ->  ZeroAtmosphericDamage.DamageCoreZero
2024-07-21 08:18:11.152 - Thread:   1 ->  SpaceEquipmentLtd.NanobotBuildAndRepairSystem.NanobotBuildAndRepairSystemMod
2024-07-21 08:18:11.154 - Thread:   1 ->  Scripts.Session
2024-07-21 08:18:11.155 - Thread:   1 ->  Scripts.Session
2024-07-21 08:18:11.155 - Thread:   1 ->  sleep.Session
2024-07-21 08:18:11.156 - Thread:   1 ->  Food_Scripts.FoodSession
2024-07-21 08:18:11.156 - Thread:   1 ->  HEX_Quiz_V2.QuizSession
2024-07-21 08:18:11.156 - Thread:   1 ->  HEX_Codeblock.Codeblock_Session
2024-07-21 08:18:11.156 - Thread:   1 ->  HEX_Autobuilder.Autobuilder_Session
2024-07-21 08:18:11.156 - Thread:   1 ->  MissionCommander.Client
2024-07-21 08:18:11.158 - Thread:   1 ->  MissionCommander.MissionCommanderSession
2024-07-21 08:18:11.159 - Thread:   1 ->  HEX_EasterBunny.EasterBunny
2024-07-21 08:18:11.159 - Thread:   1 ->  AdjustGrinderAndWelderSpeed.Example_ShipGrinderSpeed
2024-07-21 08:18:11.160 - Thread:   1 ->  Phoenix.AutoOreCollect.AutoOreAdmin
2024-07-21 08:18:11.160 - Thread:   1 ->  CharacterStats.CharacterStats
2024-07-21 08:18:11.160 - Thread:   1 ->  PerpetuallyPerturbedPirates.PPP_SessionCore
2024-07-21 08:18:11.160 - Thread:   1 ->  Digi.RotateSkyboxWithSun.RotateSkyboxMod
2024-07-21 08:18:11.160 - Thread:   1 ->  RebelBlocks_ComponentRemover.ComponentRemoverSession
2024-07-21 08:18:11.166 - Thread:   1 ->  RandomOreGenerator.RandomOreGenerator
2024-07-21 08:18:11.166 - Thread:   1 ->  PBController.PBCtrlSession
2024-07-21 08:18:11.166 - Thread:   1 ->  NotificationCloser.NotificationCloser
2024-07-21 08:18:11.168 - Thread:   1 ->  HEX_FactionAccept.AntiFactionAutoJoin
2024-07-21 08:18:11.169 - Thread:   1 ->  HEX_JumpController.JumpControllerSession
2024-07-21 08:18:11.169 - Thread:   1 ->  InstanceController.InstanceController
2024-07-21 08:18:11.169 - Thread:   1 ->  HEX_GridSurfaceRescue.GridSurfaceRescueSession
2024-07-21 08:18:11.169 - Thread:   1 ->  HEX_GravityInverter.PlanetaryGravityInverter
2024-07-21 08:18:11.169 - Thread:   1 ->  CategoryLimit.BlockCategoryLimit
2024-07-21 08:18:11.169 - Thread:   1 ->  HEX_StartMessage.VersionMessage
2024-07-21 08:18:11.169 - Thread:   1 ->  ShowAdmin.ShowAdmins
2024-07-21 08:18:11.170 - Thread:   1 ->  HEX_RespawnShipNotificator.RespawnShipNotificator
2024-07-21 08:18:11.170 - Thread:   1 ->  HEX_Clock_And_Restart.ClockAndRestart
2024-07-21 08:18:11.170 - Thread:   1 ->  Sneaky Sounds: UnloadData - START
2024-07-21 08:18:11.172 - Thread:   1 ->  Sneaky Sounds: UnloadData - END
2024-07-21 08:18:11.172 - Thread:   1 ->  SneakySounds.Mod
2024-07-21 08:18:11.172 - Thread:   1 ->  [Build Info] Unloading mod...
2024-07-21 08:18:11.179 - Thread:   1 ->  [Build Info] Mod unloaded.
2024-07-21 08:18:11.179 - Thread:   1 ->  RichHudFramework.Internal.ExceptionHandler
2024-07-21 08:18:11.179 - Thread:   1 ->  Digi.Log
2024-07-21 08:18:11.217 - Thread:   1 ->  Digi.ComponentLib.BuildInfo_GameSession
2024-07-21 08:18:11.219 - Thread:   1 ->  Digi.Dev+Unloader
2024-07-21 08:18:11.219 - Thread:   1 ->  Digi.BuildInfo.Features.CheckVSLPEvents+CheckVSLPEventsSession
2024-07-21 08:18:11.219 - Thread:   1 ->  [Build Vision] Unloading mod...
2024-07-21 08:18:11.235 - Thread:   1 ->  [Build Vision] Mod unloaded.
2024-07-21 08:18:11.236 - Thread:   1 ->  RichHudFramework.Internal.ExceptionHandler
2024-07-21 08:18:11.236 - Thread:   1 ->  RichHudFramework.UI.CmdManager
2024-07-21 08:18:11.236 - Thread:   1 ->  DarkHelmet.BuildVision2.BvApiClient
2024-07-21 08:18:11.237 - Thread:   1 ->  UIFun.ModUI
2024-07-21 08:18:11.238 - Thread:   1 ->  Digi.Log
2024-07-21 08:18:11.238 - Thread:   1 ->  Digi.CameraPanning.CameraPanningMod
2024-07-21 08:18:11.239 - Thread:   1 ->  [Rich HUD Master] Unloading mod...
2024-07-21 08:18:11.249 - Thread:   1 ->  [Rich HUD Master] Mod unloaded.
2024-07-21 08:18:11.249 - Thread:   1 ->  RichHudFramework.Internal.ExceptionHandler
2024-07-21 08:18:11.250 - Thread:   1 ->  RichHudFramework.UI.CmdManager
2024-07-21 08:18:11.251 - Thread:   1 ->  TORCH MOD: Unregistering mod communication.
2024-07-21 08:18:11.251 - Thread:   1 ->  Torch.Mod.TorchModCore
2024-07-21 08:18:11.251 - Thread:   1 ->  [SpacePedia] Unloading mod...
2024-07-21 08:18:11.256 - Thread:   1 ->  [SpacePedia] Mod unloaded.
2024-07-21 08:18:11.257 - Thread:   1 ->  RichHudFramework.Internal.ExceptionHandler
2024-07-21 08:18:11.258 - Thread:   1 ->  RichHudFramework.UI.CmdManager
2024-07-21 08:18:11.258 - Thread:   1 ->  Spacepedia.XMLParse
2024-07-21 08:18:11.258 - Thread:   1 ->  SessionComp
2024-07-21 08:18:11.258 - Thread:   1 ->  Scripts.BlockCulling.BlockCulling
2024-07-21 08:18:11.258 - Thread:   1 ->  EasyBlockRenaming.BlockRenamerCore
2024-07-21 08:18:11.259 - Thread:   1 ->  ScriptControlsToTop.MovePBControlsSession
2024-07-21 08:18:11.273 - Thread:   1 ->  Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FlightVector.Session.UnloadData()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SeamlessClient.Components.ServerSwitcherComponentOLD.UnloadSessionComponents()
   at SeamlessClient.Components.ServerSwitcherComponentOLD.UnloadCurrentServer()
   at SeamlessClient.Components.ServerSwitcherComponentOLD.<StartBackendSwitch>b__33_0()
   at Sandbox.MySandboxGame.ProcessInvoke(Boolean isClosing)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-07-21 08:18:11.280 - Thread:   1 ->  Exception occurred: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FlightVector.Session.UnloadData()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SeamlessClient.Components.ServerSwitcherComponentOLD.UnloadSessionComponents()
   at SeamlessClient.Components.ServerSwitcherComponentOLD.UnloadCurrentServer()
   at SeamlessClient.Components.ServerSwitcherComponentOLD.<StartBackendSwitch>b__33_0()
   at Sandbox.MySandboxGame.ProcessInvoke(Boolean isClosing)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-07-21 08:18:11.280 - Thread:   1 ->  InnerException: 
2024-07-21 08:18:11.280 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at FlightVector.Session.UnloadData()
2024-07-21 08:18:11.282 - Thread:   1 ->  Showing message
2024-07-21 08:18:11.283 - Thread:   1 ->  MyInitializer.OnCrash
2024-07-21 08:18:11.284 - Thread:   1 ->  var exception = System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FlightVector.Session.UnloadData()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SeamlessClient.Components.ServerSwitcherComponentOLD.UnloadSessionComponents()
   at SeamlessClient.Components.ServerSwitcherComponentOLD.UnloadCurrentServer()
   at SeamlessClient.Components.ServerSwitcherComponentOLD.<StartBackendSwitch>b__33_0()
   at Sandbox.MySandboxGame.ProcessInvoke(Boolean isClosing)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-07-21 08:18:11.853 - Thread:   1 ->  
================================== CRASH INFO ==================================
AppVersion: 01_204_018
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 235
PCUCount: 83243
IsHang: False
GCMemory: 4395
GCMemoryAllocated: 4395
HWAvailableMemory: 13066
ProcessPrivateMemory: 11438
AnalyticId: SE
================================== OFNI HSARC ==================================

2024-07-21 08:18:11.854 - Thread:   1 ->  Log Closed
```

Complete log attached: [SpaceEngineers_20240721_081415965.log](https://github.com/user-attachments/files/16323285/SpaceEngineers_20240721_081415965.log)

**Comment by Thermi** [comment]
Crash after suicide in one zone, then try to respawn in another:


```
2024-07-21 08:32:58.789 - Thread:   1 ->  ScriptControlsToTop.MovePBControlsSession
2024-07-21 08:32:58.797 - Thread:   1 ->  Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FlightVector.Session.UnloadData()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SeamlessClient.Components.ServerSwitcherComponentOLD.UnloadSessionComponents()
   at SeamlessClient.Components.ServerSwitcherComponentOLD.UnloadCurrentServer()
   at SeamlessClient.Components.ServerSwitcherComponentOLD.<StartBackendSwitch>b__33_0()
   at Sandbox.MySandboxGame.ProcessInvoke(Boolean isClosing)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-07-21 08:32:58.803 - Thread:   1 ->  Exception occurred: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FlightVector.Session.UnloadData()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SeamlessClient.Components.ServerSwitcherComponentOLD.UnloadSessionComponents()
   at SeamlessClient.Components.ServerSwitcherComponentOLD.UnloadCurrentServer()
   at SeamlessClient.Components.ServerSwitcherComponentOLD.<StartBackendSwitch>b__33_0()
   at Sandbox.MySandboxGame.ProcessInvoke(Boolean isClosing)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-07-21 08:32:58.803 - Thread:   1 ->  InnerException: 
2024-07-21 08:32:58.803 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at FlightVector.Session.UnloadData()
2024-07-21 08:32:58.804 - Thread:   1 ->  Showing message
2024-07-21 08:32:58.806 - Thread:   1 ->  MyInitializer.OnCrash
2024-07-21 08:32:58.806 - Thread:   1 ->  var exception = System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FlightVector.Session.UnloadData()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SeamlessClient.Components.ServerSwitcherComponentOLD.UnloadSessionComponents()
   at SeamlessClient.Components.ServerSwitcherComponentOLD.UnloadCurrentServer()
   at SeamlessClient.Components.ServerSwitcherComponentOLD.<StartBackendSwitch>b__33_0()
   at Sandbox.MySandboxGame.ProcessInvoke(Boolean isClosing)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-07-21 08:33:00.675 - Thread:   1 ->  
================================== CRASH INFO ==================================
AppVersion: 01_204_018
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 595
PCUCount: 126547
IsHang: False
GCMemory: 3093
GCMemoryAllocated: 3093
HWAvailableMemory: 11969
ProcessPrivateMemory: 11202
AnalyticId: SE
================================== OFNI HSARC ==================================

2024-07-21 08:33:00.676 - Thread:   1 ->  Log Closed
```

Complete log attached:  
[SpaceEngineers_20240721_08230525.log](https://github.com/user-attachments/files/16323303/SpaceEngineers_20240721_08230525.log)

**Comment by Thermi** [comment]
Crash when switching sectors while alive, reproducible.

In PluginLoader only seamless nexus is selected, no other client side mods/plugins.

```
2024-07-21 08:45:49.113 - Thread:   1 ->  SeamlessClient: Beginning Redirect to server: 90200204268549145
2024-07-21 08:45:49.568 - Thread:   1 ->  NexusSyncMod.ModCore
2024-07-21 08:45:49.569 - Thread:   1 ->  Jakaria.API.WaterModAPI
2024-07-21 08:45:49.607 - Thread:   1 ->  CoreSystems.Session
2024-07-21 08:45:49.610 - Thread:   1 ->  DefenseShields.Session
2024-07-21 08:45:49.613 - Thread:   1 ->  MIG.SpecCores.GameBase
2024-07-21 08:45:49.614 - Thread:   1 ->  Example.Mod
2024-07-21 08:45:49.615 - Thread:   1 ->  DualCockpits.CockpitSessionComponent
2024-07-21 08:45:49.615 - Thread:   1 ->  AtmosphericDamage.DamageCoreSun
2024-07-21 08:45:49.615 - Thread:   1 ->  ZeroAtmosphericDamage.DamageCoreZero
2024-07-21 08:45:49.618 - Thread:   1 ->  SpaceEquipmentLtd.NanobotBuildAndRepairSystem.NanobotBuildAndRepairSystemMod
2024-07-21 08:45:49.619 - Thread:   1 ->  Scripts.Session
2024-07-21 08:45:49.632 - Thread:   1 ->  Scripts.Session
2024-07-21 08:45:49.632 - Thread:   1 ->  sleep.Session
2024-07-21 08:45:49.633 - Thread:   1 ->  Food_Scripts.FoodSession
2024-07-21 08:45:49.633 - Thread:   1 ->  HEX_Quiz_V2.QuizSession
2024-07-21 08:45:49.634 - Thread:   1 ->  HEX_Codeblock.Codeblock_Session
2024-07-21 08:45:49.634 - Thread:   1 ->  HEX_Autobuilder.Autobuilder_Session
2024-07-21 08:45:49.635 - Thread:   1 ->  MissionCommander.Client
2024-07-21 08:45:49.636 - Thread:   1 ->  MissionCommander.MissionCommanderSession
2024-07-21 08:45:49.636 - Thread:   1 ->  HEX_EasterBunny.EasterBunny
2024-07-21 08:45:49.636 - Thread:   1 ->  AdjustGrinderAndWelderSpeed.Example_ShipGrinderSpeed
2024-07-21 08:45:49.637 - Thread:   1 ->  Phoenix.AutoOreCollect.AutoOreAdmin
2024-07-21 08:45:49.637 - Thread:   1 ->  CharacterStats.CharacterStats
2024-07-21 08:45:49.637 - Thread:   1 ->  PerpetuallyPerturbedPirates.PPP_SessionCore
2024-07-21 08:45:49.637 - Thread:   1 ->  Digi.RotateSkyboxWithSun.RotateSkyboxMod
2024-07-21 08:45:49.638 - Thread:   1 ->  RebelBlocks_ComponentRemover.ComponentRemoverSession
2024-07-21 08:45:49.641 - Thread:   1 ->  RandomOreGenerator.RandomOreGenerator
2024-07-21 08:45:49.641 - Thread:   1 ->  PBController.PBCtrlSession
2024-07-21 08:45:49.641 - Thread:   1 ->  NotificationCloser.NotificationCloser
2024-07-21 08:45:49.642 - Thread:   1 ->  HEX_FactionAccept.AntiFactionAutoJoin
2024-07-21 08:45:49.643 - Thread:   1 ->  HEX_JumpController.JumpControllerSession
2024-07-21 08:45:49.644 - Thread:   1 ->  InstanceController.InstanceController
2024-07-21 08:45:49.644 - Thread:   1 ->  HEX_GridSurfaceRescue.GridSurfaceRescueSession
2024-07-21 08:45:49.644 - Thread:   1 ->  HEX_GravityInverter.PlanetaryGravityInverter
2024-07-21 08:45:49.644 - Thread:   1 ->  CategoryLimit.BlockCategoryLimit
2024-07-21 08:45:49.644 - Thread:   1 ->  HEX_StartMessage.VersionMessage
2024-07-21 08:45:49.644 - Thread:   1 ->  ShowAdmin.ShowAdmins
2024-07-21 08:45:49.645 - Thread:   1 ->  HEX_RespawnShipNotificator.RespawnShipNotificator
2024-07-21 08:45:49.645 - Thread:   1 ->  HEX_Clock_And_Restart.ClockAndRestart
2024-07-21 08:45:49.646 - Thread:   1 ->  Sneaky Sounds: UnloadData - START
2024-07-21 08:45:49.648 - Thread:   1 ->  Sneaky Sounds: UnloadData - END
2024-07-21 08:45:49.648 - Thread:   1 ->  SneakySounds.Mod
2024-07-21 08:45:49.649 - Thread:   1 ->  [Build Info] Unloading mod...
2024-07-21 08:45:49.656 - Thread:   1 ->  [Build Info] Mod unloaded.
2024-07-21 08:45:49.657 - Thread:   1 ->  RichHudFramework.Internal.ExceptionHandler
2024-07-21 08:45:49.657 - Thread:   1 ->  Digi.Log
2024-07-21 08:45:49.698 - Thread:   1 ->  Digi.ComponentLib.BuildInfo_GameSession
2024-07-21 08:45:49.699 - Thread:   1 ->  Digi.Dev+Unloader
2024-07-21 08:45:49.699 - Thread:   1 ->  Digi.BuildInfo.Features.CheckVSLPEvents+CheckVSLPEventsSession
2024-07-21 08:45:49.700 - Thread:   1 ->  [Build Vision] Unloading mod...
2024-07-21 08:45:49.719 - Thread:   1 ->  [Build Vision] Mod unloaded.
2024-07-21 08:45:49.720 - Thread:   1 ->  RichHudFramework.Internal.ExceptionHandler
2024-07-21 08:45:49.720 - Thread:   1 ->  RichHudFramework.UI.CmdManager
2024-07-21 08:45:49.721 - Thread:   1 ->  DarkHelmet.BuildVision2.BvApiClient
2024-07-21 08:45:49.723 - Thread:   1 ->  UIFun.ModUI
2024-07-21 08:45:49.724 - Thread:   1 ->  Digi.Log
2024-07-21 08:45:49.725 - Thread:   1 ->  Digi.CameraPanning.CameraPanningMod
2024-07-21 08:45:49.725 - Thread:   1 ->  [Rich HUD Master] Unloading mod...
2024-07-21 08:45:49.739 - Thread:   1 ->  [Rich HUD Master] Mod unloaded.
2024-07-21 08:45:49.739 - Thread:   1 ->  RichHudFramework.Internal.ExceptionHandler
2024-07-21 08:45:49.740 - Thread:   1 ->  RichHudFramework.UI.CmdManager
2024-07-21 08:45:49.741 - Thread:   1 ->  TORCH MOD: Unregistering mod communication.
2024-07-21 08:45:49.741 - Thread:   1 ->  Torch.Mod.TorchModCore
2024-07-21 08:45:49.741 - Thread:   1 ->  [SpacePedia] Unloading mod...
2024-07-21 08:45:49.747 - Thread:   1 ->  [SpacePedia] Mod unloaded.
2024-07-21 08:45:49.748 - Thread:   1 ->  RichHudFramework.Internal.ExceptionHandler
2024-07-21 08:45:49.749 - Thread:   1 ->  RichHudFramework.UI.CmdManager
2024-07-21 08:45:49.749 - Thread:   1 ->  Spacepedia.XMLParse
2024-07-21 08:45:49.749 - Thread:   1 ->  SessionComp
2024-07-21 08:45:49.749 - Thread:   1 ->  Network readers disposed
2024-07-21 08:45:50.216 - Thread:   1 ->  SeamlessClient: Successfully set MyMultiplayer.Static
2024-07-21 08:45:50.222 - Thread:   1 ->  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreSystems.Session.HandleInput()
   at Sandbox.Game.World.MySession.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-07-21 08:45:50.228 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreSystems.Session.HandleInput()
   at Sandbox.Game.World.MySession.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-07-21 08:45:50.229 - Thread:   1 ->  Showing message
2024-07-21 08:45:50.231 - Thread:   1 ->  MyInitializer.OnCrash
2024-07-21 08:45:50.231 - Thread:   1 ->  var exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreSystems.Session.HandleInput()
   at Sandbox.Game.World.MySession.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-07-21 08:45:51.940 - Thread:   1 ->  
================================== CRASH INFO ==================================
AppVersion: 01_204_018
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 250
PCUCount: 0
IsHang: False
GCMemory: 4498
GCMemoryAllocated: 4498
HWAvailableMemory: 11861
ProcessPrivateMemory: 10102
AnalyticId: SE
================================== OFNI HSARC ==================================

2024-07-21 08:45:51.940 - Thread:   1 ->  Log Closed
```

Complete log attached: 
[SpaceEngineers_20240721_084141722.log](https://github.com/user-attachments/files/16323316/SpaceEngineers_20240721_084141722.log)

**Comment by Thermi** [comment]
Crash ONLY REPRODUCIBLE with seamless nexus plugin. SE does not crash without pluginloader, and also does not crash with pluginloader and no mods.

It crashes with pluginloader and seamless nexus.

**Comment by Thermi** [comment]
@Casimir255 logs are here if you didn't find them already

**Comment by Casimir255** [comment]
I reverted to what it was before I started messing with it last night

**Comment by Thermi** [comment]
Thank you!
