### ISSUE TITLE
Crash with WeaponCore mods

### ISSUE THREAD

**Issue by Diamantino-Op** [Casimir255/SeamlessClient#3]
I play in the server Stone Industries, and seem to crash the game when we are in king of the hill and an enemy approaches with modded weapons, is it possible to fix this crash?

**Comment by Casimir255** [comment]
Need logs

**Comment by Diamantino-Op** [comment]
Yeah srry, here it is: https://drive.google.com/file/d/1ueuSU31VKLxiFshlTgWueG1HnW3NqEZl/view?usp=sharing (had to upload here bc it was more than 25Mb)

**Comment by Casimir255** [comment]
2023-12-06 20:22:34.046 - Thread:   1 ->  STATISTICS,14724.9666667,0.07328415,0.008263588,3.091935,1.034287,651.824,95.20287,239.3234,518.2988,8,149,8507.021,28470.46,377692,500000,14,94.81817,70.46243,0.02523918,31978,19.79456,1,16.66667,18.76884,13.94773,100,14698847614,8507.021,0,1,-1
2023-12-06 20:22:34.046 - Thread:   1 ->  MEMORY LEGEND,Srv,Uav,Read,Debug,Index,Audio,SrvUav,Vertex,Buffers,Physics,Planets,Systems,Textures,Indirect,Constant,RwTextures,Dx11Render,MeshBuffers,FileTextures,DepthStencil,TileTextures,Voxels-Native,CustomTextures,HeightmapFaces,Mesh GPU Buffers,BitStreamBuffers,GeneratedTextures,FileArrayTextures,NativeDictionaries,CubemapDataBuffers,HeightDetailTexture,MyDeviceWriteBuffers,ShadowCascadesStatsBuffers,AI_PathFinding,EpicOnlineServices,EpicOnlineServicesWrapper
2023-12-06 20:22:34.046 - Thread:   1 ->  MEMORY VALUES,2,1,0,1,191,995,281,869,1461,309,2419,14017,8026,0,0,430,9488,0,5375,126,0,5,63,629,74,38,38,1723,759,1777,13,40,0,0,0,0
2023-12-06 20:22:42.984 - Thread:   1 ->  Loading voxel storage from file 'F:\Steam Library\steamapps\common\SpaceEngineers\Content\VoxelMaps\Many_Small_Asteroids.vx2'
2023-12-06 20:22:42.986 - Thread:   1 ->  CRITICAL-VOXEL MAP!!! ---- VoxelMap already loaded. This must not happen (Asteroid_512219159_575692166_0)
2023-12-06 20:22:43.029 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.World.Generator.MyEncounterGenerator.RegisterEntityToEncounter(MyEncounterId id, MyEntity entity)
   at Sandbox.Game.World.Generator.MyEncounterGenerator.PlaceEncounterToWorld(BoundingBoxD boundingVolume, Int32 seed)
   at Sandbox.Game.World.Generator.MyProceduralAsteroidCellGenerator.GenerateObjects(List`1 objectsList, HashSet`1 existingObjectsSeeds)
   at Sandbox.Game.World.Generator.MyProceduralWorldGenerator.GenerateIfNeeded(MyEntityTracker tracker)
   at Sandbox.Game.World.Generator.MyProceduralWorldGenerator.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)

**Comment by Casimir255** [comment]
@Diamantino-Op I informed your admins at SI to fix the whole log spam stuff. Quite annoying with all of the 
2023-12-06 14:53:30.067 - Thread:   1 ->  BOING:    at Zebedee.Zebedee.UpdateAfterSimulation()
2023-12-06 14:53:30.081 - Thread:   1 ->  BOING:    at Zebedee.Zebedee.UpdateAfterSimulation()
2023-12-06 14:53:30.096 - Thread:   1 ->  BOING:    at Zebedee.Zebedee.UpdateAfterSimulation()
2023-12-06 14:53:30.123 - Thread:   1 ->  BOING:    at Zebedee.Zebedee.UpdateAfterSimulation()
2023-12-06 14:53:30.137 - Thread:   1 ->  BOING:    at Zebedee.Zebedee.UpdateAfterSimulation()
2023-12-06 14:53:30.152 - Thread:   1 ->  BOING:    at Zebedee.Zebedee.UpdateAfterSimulation()
2023-12-06 14:53:30.164 - Thread:   1 ->  BOING:    at Zebedee.Zebedee.UpdateAfterSimulation()
2023-12-06 14:53:30.179 - Thread:   1 ->  BOING:    at Zebedee.Zebedee.UpdateAfterSimulation()
2023-12-06 14:53:30.245 - Thread:   1 ->  BOING:    at Zebedee.Zebedee.UpdateAfterSimulation()

At any case your crash might be an issue with seamless and MES/encounters spawning with roids. I'll have to look into it further

**Comment by Diamantino-Op** [comment]
ok, thx

**Comment by Diamantino-Op** [comment]
I have another log, this time it crashed while trying to load a ship
[message.txt](https://github.com/Casimir255/SeamlessClient/files/13761903/message.txt)

**Comment by Casimir255** [comment]
Mods are now being reloaded on seamless transfers. Please let me know if this helps anything with WC
